### ISSUE TITLE
:animationData="require('@/assets/animation.json')" doesn't work with Vite

### ISSUE THREAD

**Issue by rhclayto** [garbit/lottie-web-vue#17]
The Vue 3 example has `:animationData="require('@/assets/animation.json')"` in the template. However, `require` fails when using Vite. Is there an alternative way of telling lottie-web-view what animation data file to use?

**Comment by rhclayto** [comment]
I found out how to make it work with Vite:

```js
import animationURL from '@/assets/animations/spinningLogo.json';
<lottie-animation
  ref="anim"
  :animationData="animationURL"
/>
```

Please consider adding this to the Readme.

**Comment by garbit** [comment]
Hi @rhclayto, thank you for highlighting this issue. I've updated the README in response to your feedback. 

Please see: https://github.com/garbit/lottie-web-vue/commit/65fad4684edfeb0002e48aa731c30e2e6f0b941f

**Comment by rhclayto** [comment]
Great! Perfect!
