### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by Noxdor** [garbit/lottie-web-vue#6]
I am trying to include a lottie animation in a vue 3 project with snowpack. Unfortunately no animation shows up and I get an error from the vue rendering engine:

```
TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.__vue_render__ (lottie-web-vue.v1.2.0.js:151)
    at renderComponentRoot (@vue.runtime-core.v3.2.22.js:232)
    at ReactiveEffect.componentUpdateFn [as fn] (@vue.runtime-core.v3.2.22.js:3301)
    at ReactiveEffect.run (@vue.reactivity.v3.2.22.js:149)
    at setupRenderEffect (@vue.runtime-core.v3.2.22.js:3383)
    at mountComponent (@vue.runtime-core.v3.2.22.js:3237)
    at processComponent (@vue.runtime-core.v3.2.22.js:3208)
    at patch (@vue.runtime-core.v3.2.22.js:2855)
    at mountChildren (@vue.runtime-core.v3.2.22.js:3017)
    at mountElement (@vue.runtime-core.v3.2.22.js:2942)
```

I tried to stick as closely as possible to the example but had to change it a little to work with snowpack. I tried to confirm the correct input into the lottie-player tag by printing out both the animation and lottie-animation tag, both appear fine. This is my code:

```js
<template>
    <div>
        <lottie-animation
        ref="anim"
        :animationData="animation"
        :loop="true"
        />
    </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from "vue"
import LottieAnimation from "lottie-web-vue"    
import animation from "../../../assets/settings/theme_lottie.json"

export default defineComponent({
    components: {
        LottieAnimation,
    },
    setup() {
        const anim : any = ref(null)

        onMounted(() => {
            // the DOM element will be assigned to the ref after initial render
            console.log(anim)
            console.log(animation)
            anim.value.play()
        })

        return {
            anim,
            animation,
        }
    },
})
</script>

```

Do you have any idea why it is not working and what I might be doing wrong? Help is greatly appreciated!

**Comment by urbgimtam** [comment]
Same here, using vue3 without typescript.
Works great in Vue 2, though.

**Comment by reslear** [comment]
same vue3, how to fix?

**Comment by garbit** [comment]
Thanks for raising this @Noxdor - will take a look and reproduce. Any chance you could create a test repo so I could check it out?

**Comment by JohanManders** [comment]
I think I have the same problem, see: https://codesandbox.io/s/infallible-snowflake-mknvm

**Comment by megasanjay** [comment]
Is there any update to this? I'm still getting this error on Nuxt

**Comment by garbit** [comment]
Hi Sanjay,

I've been working on a branch to try and upgrade to vue 3 which I'll try
push in the next few days once I have it working.

Apologies for the delay.

**Comment by sashaadazhii** [comment]
Hello. Vue3 - problem still exists.

**Comment by megasanjay** [comment]
I think the author might be too busy. I ended up creating my own library to handle my Lottie implementations. Although truth be told you can do everything without a library too as I found out. I really dislike doing this on another OSS project but if anyone needs a maintained package: https://github.com/megasanjay/vue3-lottie

**Comment by garbit** [comment]
Hi all, I've now added Vue 3 support to the plugin. My apologies for the delay!

Thanks @megasanjay for stepping in and assisting in the meanwhile - your implementation has great documentation.

Thank you all for your patience.
