### ISSUE TITLE
is playSegments and goToAndPlay events missing?

### ISSUE THREAD

**Issue by Anders3byg** [garbit/lottie-web-vue#9]
E.g this.$refs.bell.playSegments([75, 95], true);

Or 

this.$refs.confetti.goToAndPlay(0, true)

**Comment by garbit** [comment]
Hi @Anders3byg, as of the latest release [```v2.0.4```](https://github.com/garbit/lottie-web-vue/releases/tag/v2.0.4) you can now use:

```js
this.$refs.anim.goToAndPlay(position, isFrame)
```
- **Position** is the frame number or seconds into the animation you with to goToAndPlat
- **isFrame** (pass true/false) defines if ```Position``` is a ```frame number``` or ```seconds```.

Hope this resolves your issue!
